### PR TITLE
Clean up imports and fix docs

### PR DESCRIPTION
**Pull request by themysticsavages**
I removed modules imported more than once in `main.py`, as well as removing exception catching for WebSocket initialization. In addition to that, I used the requirements.txt for installation in `README.md`.

While it looks like I may be doing this again, the commits I made previously did not merge. That's why I'm doing it again.

### CODE REVIEW

**Comment by FuchsCrafter** [comment]
To the commit problem: Cloud Firstly merged you pull request and then mine. Because I do not used your version of the file it got back to the old version. Sorry for that!

**Comment by themysticsavages** [comment]
@FuchsCrafter It's alright. Next time anyone makes a pull request, just go to your fork and press "Fetch upstream". It will commit all the contents of the-cloud-dev's repository to your fork. (You probably know this already, but maybe not)

**Comment by themysticsavages** [comment]
Ok, it looks like the changes were merged.

**Comment by FuchsCrafter** [comment]
> @FuchsCrafter It's alright. Next time anyone makes a pull request, just go to your fork and press "Fetch upstream". It will commit all the contents of the-cloud-dev's repository to your fork. (You probably know this already, but maybe not)
@themysticsavages 

No, I didn't knew that, but I will do this next time 🙂

**Comment by themysticsavages** [comment]
@FuchsCrafter OK

**Comment by themysticsavages** [comment]
Closing this PR since most issues are already resolved!

**Pull request closed without merging**
